import type { Card } from "./types";

// ─────────────────────────────────────────────────────────────────────────
// THE STORY
//
// This array IS the app. Each entry is one full-screen card, shown in order.
// Edit the copy freely. Photo paths are relative to /public.
// ─────────────────────────────────────────────────────────────────────────

export const STORY: Card[] = [
  {
    kind: "cover",
    theme: "berry",
    title: "Hannah + James",
    subtitle: "Wrapped · 2.5 Years",
    photo: "/photos/cover/cover.jpg",
  },
  {
    kind: "text",
    theme: "night",
    eyebrow: "Before we begin",
    title: "Two and a half years. Our amazing story.",
    body: "Here are some highlights. Tap to keep going.",
  },
  {
    kind: "text",
    theme: "plum",
    eyebrow: "December 21, 2023",
    title: "The start of something new.",
    body: "It feels so right, to be here with you",
  },
  {
    kind: "photo",
    theme: "rose",
    eyebrow: "Our first date",
    photo: "/photos/highlights/first-date.jpg",
    caption: "Where it all began.",
  },
  {
    kind: "bigNumber",
    theme: "berry",
    pre: "Since that night, that's",
    value: "daysTogether",
    label: "days together",
    sub: "…not that anyone's counting.",
  },
  {
    kind: "gallery",
    theme: "night",
    title: "A few of our favorite moments",
    subtitle:
      "Even from across the world, you're still the best part of every day.",
    items: [
      { photo: "/photos/moments/1.jpg" },
      { photo: "/photos/moments/2.jpg" },
      { photo: "/photos/moments/3.jpg" },
      { photo: "/photos/moments/4.jpg" },
      { photo: "/photos/moments/5.jpg" },
      { photo: "/photos/moments/6.jpg" },
    ],
  },
  {
    kind: "statList",
    theme: "plum",
    title: "By the numbers",
    items: [
      { label: "Vacations taken", value: "6(+)" },
      { label: "Trips to Disney", value: "2 🏰" },
      { label: "Hugs", value: "Infinite" },
      { label: "Rings acquired", value: "1 💍" },
    ],
  },
  {
    kind: "text",
    theme: "sunset",
    eyebrow: "Chapter two",
    title: "Memory Highlights",
    body: "Our favorite places, faces, and two very well-traveled mushrooms.",
  },
  {
    kind: "vacation",
    theme: "gold",
    place: "Las Vegas",
    emoji: "🎰",
    blurb: "What happens in Vegas… becomes some of our favorite stories.",
    photo: "/photos/highlights/vegas.jpg",
  },
  {
    kind: "vacation",
    theme: "night",
    place: "Washington, D.C.",
    emoji: "🏛️",
    blurb: "Monuments, museums, and a lot of walking. Worth every step.",
    photo: "/photos/highlights/dc.jpg",
  },
  {
    kind: "gallery",
    theme: "berry",
    emoji: "🐱",
    title: "Caterpillar",
    subtitle: "Our son is the best.",
    items: [
      { photo: "/photos/caterpillar/1.jpg" },
      { photo: "/photos/caterpillar/2.jpg" },
    ],
  },
  {
    kind: "vacation",
    theme: "plum",
    place: "Frankenmush",
    emoji: "🎄",
    dates: "A Christmush tradition",
    blurb: "Zehnder's, twinkle lights, and chicken dinners — every year.",
    photo: "/photos/highlights/frankenmush.jpg",
  },
  {
    kind: "gallery",
    theme: "rose",
    emoji: "🍄",
    title: "Mush Around the World",
    subtitle:
      "Our travel buddy, posing her way through the World Showcase. Shockingly, she's not pissed.",
    collage: true,
    items: [
      { photo: "/photos/mush/01.jpg" },
      { photo: "/photos/mush/02.jpg" },
      { photo: "/photos/mush/03.jpg" },
      { photo: "/photos/mush/04.jpg" },
      { photo: "/photos/mush/05.jpg" },
      { photo: "/photos/mush/06.jpg" },
      { photo: "/photos/mush/07.jpg" },
      { photo: "/photos/mush/08.jpg" },
      { photo: "/photos/mush/09.jpg" },
      { photo: "/photos/mush/10.jpg" },
    ],
  },
  {
    kind: "vacation",
    theme: "sunset",
    place: "Santa Barbara",
    emoji: "🌅",
    blurb: "Even rain can't stop us from having a great time.",
    photo: "/photos/highlights/santa-barbara.jpg",
  },
  {
    kind: "vacation",
    theme: "plum",
    place: "Chicago",
    emoji: "🌆",
    blurb: "Deep dish, the skyline, and the cold for our two-year anniversary!",
    photo: "/photos/highlights/chicago.jpg",
  },
  {
    kind: "gallery",
    theme: "night",
    emoji: "🏟️",
    title: "Michigan",
    subtitle: "Hail to the Victors.",
    items: [
      { photo: "/photos/michigan/1.jpg" },
      { photo: "/photos/michigan/2.jpg" },
    ],
  },
  {
    kind: "vacation",
    theme: "rose",
    place: "Disney World",
    emoji: "🏰",
    dates: "Round two",
    blurb: "Round two, and many more to come.",
    photo: "/photos/highlights/disney2.jpg",
  },
  {
    kind: "text",
    theme: "night",
    eyebrow: "Then, this year…",
    title: "Best. Surprise. Ever.",
    body: "March 7, 2026.",
  },
  {
    kind: "proposal",
    theme: "rose",
    date: "March 7, 2026",
    photo: "/photos/proposal/1.jpg",
  },
  {
    kind: "text",
    theme: "berry",
    eyebrow: "From a first date…",
    title: "…to a forever date.",
  },
  {
    kind: "countdown",
    theme: "night",
    eyebrow: "Coming soon",
    title: "The Wedding",
    target: "2027-07-04T00:00:00",
    footnote: "Fireworks for our future.",
  },
  {
    kind: "outro",
    theme: "berry",
    title: "To be continued…",
    body: "Here's to every hug, every Disney adventure, and every day still to come. I love you, I miss you, and I can't wait to see you soon! — James",
  },
];
